# -*- mode: ruby -*-
# vi: set ft=ruby sw=2 ts=2 sts=2 et :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider :openstack do |os, override|
    config.vm.box = "dummy"

    if ENV['IMAGE']
      os.image = ENV['IMAGE']
    else
      os.image = 'BAD IMAGE'
      override.ssh.username = 'baduser'
    end

  case ENV['IMAGE']
      when /.*ubuntu.*/i
        override.ssh.username = 'ubuntu'

      when /.*fedora.*/i
        override.ssh.username = 'fedora'

        # take care of the tty requirement by fedora for sudo
        os.user_data = "#!/bin/bash
/bin/sed -i 's/ requiretty/ !requiretty/' /etc/sudoers;"

      when /.*centos.*/i
        override.ssh.username = 'centos'

        # take care of the tty requirement by centos for sudo
        os.user_data = "#!/bin/bash
/bin/sed -i 's/ requiretty/ !requiretty/' /etc/sudoers;"
    end
  end

  config.vm.provision 'shell', path: 'bootstrap.sh'
end
