#!/usr/bin/python
# -*- coding: utf-8 -*-

# @License EPL-1.0 <http://spdx.org/licenses/EPL-1.0>
##############################################################################
# Copyright (c) 2015 Mohammed Hassan Zahraee and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
##############################################################################

from spectrometer.datacollector import collect_n_store
import multiprocessing
import argparse
import os

from spectrometer import create_app

parser = argparse.ArgumentParser()
parser.add_argument("-c", "--conf", help="Config file")
args = parser.parse_args()

config = os.path.join(os.getcwd(), 'config.py')
if args.conf:
    config = os.path.realpath(args.conf)

app = create_app(config)
p = multiprocessing.Process(target=collect_n_store,
                            args=(app.config['REPOSITORY_ADDRESSES'],)
                            )
p.start()

app.run(debug=True)
